version: '3.8'
services:
    api-meta-store:
        build: .
        image: registry.gitlab.com/dataware-tools/api-meta-store:latest
        container_name: api-meta-store
        environment:
          PORT: 8080
#          API_DEBUG: 'true'
          PYDTK_META_DB_ENGINE: 'tinymongo'
          PYDTK_META_DB_HOST: '/opt/app/test/assets/test_v4'
        volumes:
            - .:/opt/app:rw
        ports:
            - 8080:8080
        working_dir: /opt/app
        command: python api/server.py
        tty: true
